version: "3"

services:
  htn_explorer:
    container_name: htn_explorer
    image: supertypo/htn-explorer:latest
    restart: unless-stopped
    environment:
      API_URI: "http://localhost:8000"
      API_WS_URI: "ws://localhost:8000"
    ports:
      - "8080:8080/tcp"

  htn_rest_server:
    container_name: htn_rest_server
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    restart: unless-stopped
    command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000 
    volumes:
      - "../:/app"
    environment:
      VECNOD_HOST_1: vecnod:42420
      SQL_URI: postgresql+asyncpg://postgres:postgres@postgresql:5432/postgres
    ports:
      - "8000:8000/tcp"
    links:
      - vecnod
      - postgresql

  htn_db_filler:
    container_name: htn_db_filler
    image: supertypo/htn-db-filler:latest
    restart: unless-stopped
    environment:
      DEBUG: "true"
      VECNOD_HOST_1: vecnod:42420
      SQL_URI: postgresql://postgres:postgres@postgresql:5432/postgres
    links:
      - vecnod
      - postgresql

  postgresql:
    container_name: postgresql
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - postgresql:/var/lib/postgresql/data/

  vecnod:
    container_name: vecnod
    image: supertypo/vecnod:latest
    restart: unless-stopped
    ports:
      - "42420:42420/tcp"
      - "16111:16111/tcp"
    volumes:
      - vecnod:/app/data/
    command: vecnod --utxoindex --connect=kdxweb.htncalc.net

volumes:
  postgresql:
  vecnod:
